### ISSUE TITLE
OS fetching dosen't work

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1036]
This is visible when using DXVK verb. Linux users get the message for Mac users. 
This section needs to be checked:
```
if (operatingSystemFetcher.fetchCurrentOperationSystem() != "Linux")
    {
        this.wizard().message(tr("DXVK might not work correctly on macOS. This is depending on Metal api support and MoltenVK compatibility layer advancement"));
    }
    else
    {
        this.wizard().message(tr("Please ensure you have the latest drivers (418.30 minimum for NVIDIA and mesa 19 for AMD) or else DXVK might not work correctly."));
    }
```
I've already tried replacing != with !== but it changed nothing.

**Comment by qparis** [comment]
OperatingSystemFetcher#fetchCurrentOperationSystem retuns a fetchCurrentOperationSystem object, not a string. You may want to try getFullName() method

**Comment by qparis** [comment]
(See https://github.com/PhoenicisOrg/phoenicis/blob/master/phoenicis-tools/src/main/java/org/phoenicis/tools/system/OperatingSystemFetcher.java)

**Comment by Zemogiter** [comment]
OK so after I saw OperatingSystemFetcher I made this modification to DXVK script:
```
    var operatingSystem = Bean("operatingSystemFetcher");
    print("NOTE: wine version should be greater or equal to 3.10");
    if (operatingSystem.fromString(operatingSystem.getProperty("os.name")) != "Linux")
    {
        this.wizard().message(tr("DXVK might not work correctly on macOS. This is depending on Metal api support and MoltenVK compatibility layer advancement"));
    }
    else
    {
        this.wizard().message(tr("Please ensure you have the latest drivers (418.30 minimum for NVIDIA and mesa 19 for AMD) or else DXVK might not work correctly."));
    }
```
But I got this:
```[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: invokeMember on JavaObject[org.phoenicis.tools.system.OperatingSystemFetcher@722d9fa3 (org.phoenicis.tools.system.OperatingSystemFetcher)] failed due to: Unknown identifier: getProperty
	at <js> Wine.DXVK(engines.wine.verbs.dxvk:16:575-612)
	at <js> install(engines.wine.verbs.dxvk:107:3970-4000)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:360)
	at org.phoenicis.engines.Verb$$JSJavaAdapter.install(Unknown Source)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:67)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-3-thread-7" TypeError: invokeMember on JavaObject[org.phoenicis.tools.system.OperatingSystemFetcher@722d9fa3 (org.phoenicis.tools.system.OperatingSystemFetcher)] failed due to: Unknown identifier: getProperty
	at <js> Wine.DXVK(engines.wine.verbs.dxvk:16:575-612)
	at <js> install(engines.wine.verbs.dxvk:107:3970-4000)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:360)
	at org.phoenicis.engines.Verb$$JSJavaAdapter.install(Unknown Source)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:67)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by plata** [comment]
Try
```Javascript
if (operatingSystemFetcher.fetchCurrentOperationSystem().getFullName() !== "Linux")
```

**Comment by Zemogiter** [comment]
Solved.
