### ISSUE TITLE
Error during Notepad++ Installation

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1059]
When installing Notepad++ I get the following error:

```
Exception in thread "pool-3-thread-4" Ausführbare Datei Notepad++.exe nicht gefunden!
	at <js> create(engines.wine.shortcuts.wine:154:4119-4170)
	at <js> _createShortcut(engines.wine.quick_script.quick_script:157:3833-3849)
	at <js> go(engines.wine.quick_script.installer_script:83:3701-3735)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy44.go(Unknown Source)
	at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Translated this means: `Executable Notepad++.exe not found!` When looking in the prefix folder I discovered that the folder seems to be unpopulated, i.e. I couldn't find any Notepad++ files inside it.

Any ideas?

**Comment by plata** [comment]
Do you still have this after #1057 (this exact issue was the reason for me to implement that)?

**Comment by madoar** [comment]
Yes I still get the same error message. Does it work for you?

**Comment by Zemogiter** [comment]
Can't reproduce under latest POL5 repo and script repo.

**Comment by plata** [comment]
I have to disable the runtime in `LD_LIBRARY_PATH` but apart from that it works.

**Comment by madoar** [comment]
I get the same result with a fresh `.Phoenicis` folder on the current master branch.

**Comment by madoar** [comment]
I just found a maybe useful `wine.log` file in my "empty" container folder:

```
003e:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003e:err:winediag:nodrv_CreateWindow Unknown error (127).
```

**Comment by plata** [comment]
Can you try without the runtime in `LD_LIBRARY_PATH`?
Change here: https://github.com/PhoenicisOrg/scripts/blob/98eab66312151340d604f218cab1040abde45542/Engines/Wine/Engine/Implementation/script.js#L423
```Javascript
if (architecture == "amd64") {
            ldPath = this.getLocalDirectory(subCategory, version) + "/lib64/:"
                + this.getLocalDirectory(subCategory, version) + "/lib/:" + ldPath;
        } else {
            ldPath = this.getLocalDirectory(subCategory, version) + "/lib/:" + ldPath;
}
```

**Comment by madoar** [comment]
@plata after using your suggested change it is working.

**Comment by plata** [comment]
See #1056.

**Comment by madoar** [comment]
It is working now after the runtime has been rebuilt
