### ISSUE TITLE
Steam does not work

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1098]
When using a SteamScript, the exe process is displayed and you get the usual "connecting to the steam account" messages. But after that the .exe shuts itself down and nothing happens. Tested using `Space Engineers` prefix with all upstream wine versions between 4.0.1 and 4.14 same results
```
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
001b:err:setupapi:SetupDiSelectBestCompatDrv No compatible drivers were enumerated for device L"WINEMOUSE\\VID_0000&PID_0000\\0&WINEMOUSE&0&0".
001b:err:plugplay:install_device_driver Install function 0x17 failed, error 0xe0000228.
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:msi:execute_command unable to execute command 2
0025:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib64/wine/winegstreamer.dll.so": /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0: undefined symbol: gst_aggregator_simple_get_next_time
0055:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winegstreamer.dll.so": /lib/i386-linux-gnu/libgstaudio-1.0.so.0: undefined symbol: gst_aggregator_simple_get_next_time
wine: configuration in '/home/jonasz/.Phoenicis/containers//wineprefix//Space Engineers' has been updated.
[0823/111145:ERROR:network_change_notifier_win.cc(170)] WSALookupServiceBegin failed with: 122
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/hwine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
001b:err:setupapi:SetupDiSelectBestCompatDrv No compatible drivers were enumerated for device L"WINEMOUSE\\VID_0000&PID_0000\\0&WINEMOUSE&0&0".
001b:err:plugplay:install_device_driver Install function 0x17 failed, error 0xe0000228.
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:mscoree:LoadLibraryShim error reading registry key for installroot
0039:err:msi:execute_command unable to execute command 2
0025:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib64/wine/winegstreamer.dll.so": /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0: undefined symbol: gst_aggregator_simple_get_next_time
0055:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winegstreamer.dll.so": /lib/i386-linux-gnu/libgstaudio-1.0.so.0: undefined symbol: gst_aggregator_simple_get_next_time
wine: configuration in '/home/jonasz/.Phoenicis/containers//wineprefix//Space Engineers' has been updated.
[0823/111145:ERROR:network_change_notifier_win.cc(170)] WSALookupServiceBegin failed with: 122
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:create_server class {bcde0395-e52f-467c-8e3d-c4579291692e} not registered
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x17
\src\clientdll\controllerabstraction.cpp (5798) : Assertion Failed: Unrecognized Xinput Controller: 0x810, 0xe501
\src\clientdll\controllerabstraction.cpp (5798) : Assertion Failed: Unrecognized Xinput Controller: 0x810, 0xe501
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:create_server class {bcde0395-e52f-467c-8e3d-c4579291692e} not registered
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x17ome/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:create_server class {bcde0395-e52f-467c-8e3d-c4579291692e} not registered
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x17
\src\clientdll\controllerabstraction.cpp (5798) : Assertion Failed: Unrecognized Xinput Controller: 0x810, 0xe501
\src\clientdll\controllerabstraction.cpp (5798) : Assertion Failed: Unrecognized Xinput Controller: 0x810, 0xe501
008a:err:module:load_so_dll failed to load .so lib "/home/jonasz/.Phoenicis/engines/wine/upstream-linux-amd64/4.14/bin/../lib/wine/winepulse.drv.so": libpulsecommon-10.0.so: nie można otworzyć pliku obiektu dzielonego: Nie ma takiego pliku ani katalogu
008a:err:mmdevapi:DllGetClassObject Driver initialization failed
008a:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
008a:err:ole:create_server class {bcde0395-e52f-467c-8e3d-c4579291692e} not registered
008a:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x17
```
The text in polish means can't open shared object file: no file or directory found.

**Comment by ImperatorS79** [comment]
I guess we need to add libpulsecommon-10.0.so to the runtime, since on ubuntu it is libpulsecommon-12.2.so

**Comment by Zemogiter** [comment]
Putting that .so file in runtime locally fixed this issue.

**Comment by ImperatorS79** [comment]
Great, I will add it to the runtime then

**Comment by Zemogiter** [comment]
Now this is weird. I was able to install and run Space Engineers but now when I'm trying to launch it (manually selecting steam.exe because the shortuct seems to be broken for steam scripts, needs to validate) I get errors mentioning libICE.so.6 not found
Haven't made any changes to the prefix.

**Comment by ImperatorS79** [comment]
Could you do the same than before with that lib ? https://packages.debian.org/stretch/libice6

**Comment by Zemogiter** [comment]
Already done but form buster branch instead of stretch. With that file inside the runtime folder steam returned to normal. Lets see for how long :grimacing:

**Comment by ImperatorS79** [comment]
okay, one more lib to add!
If you encounter missing libs, please test like you did here and open a PR in phoenicis-winebuild directly ^^

**Comment by plata** [comment]
Other question: do you have this issue also if you do not use the runtime (i.e. remove it from `ldPath` in Wine implementation)?

**Comment by Zemogiter** [comment]
@plata haven't tested that

**Comment by plata** [comment]
Could you do so? I would really be interested in the result.

**Comment by Zemogiter** [comment]
Do you mean removing every line mentioning `ldPath` in `engines.wine.engine.implementation`?

**Comment by plata** [comment]
Change the code here:
https://github.com/PhoenicisOrg/scripts/blob/773a6dd909fe9869a7412d9765676b32613d18fd/Engines/Wine/Engine/Implementation/script.js#L439
to:
```Javascript
if (architecture == "amd64") {
    ldPath =
        this.getLocalDirectory(subCategory, version) +
        "/lib64/:" +
        this.getLocalDirectory(subCategory, version) +
        "/lib/:" +
        ldPath;
} else {
    ldPath =

        this.getLocalDirectory(subCategory, version) +
        "/lib/:" +
        ldPath;
}
```

**Comment by Zemogiter** [comment]
Just did the change and I get this error:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - SyntaxError: Unexpected end of input
	at <js> _installRuntime(Unnamed:146:5719-5748)
	at <js> install(Unnamed:40:1847-1884)
	at <js> run(Unnamed:370:13940-13973)
	at <js> run(Unnamed:170:5379-5469)
	at <js> run(Unnamed:39-41:1232-1396)
	at <js> run(Unnamed:107:3183-3212)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy44.run(Unknown Source)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:52)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-3-thread-6" SyntaxError: Unexpected end of input
	at <js> _installRuntime(Unnamed:146:5719-5748)
	at <js> install(Unnamed:40:1847-1884)
	at <js> run(Unnamed:370:13940-13973)
	at <js> run(Unnamed:170:5379-5469)
	at <js> run(Unnamed:39-41:1232-1396)
	at <js> run(Unnamed:107:3183-3212)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy44.run(Unknown Source)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:52)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
However I had it yesterday before any change was made to implementation.

**Comment by ImperatorS79** [comment]
I got that to, maybe a problem with the server ?

**Comment by madoar** [comment]
This should be a syntax error in the script (maybe a `{`/`}` to much or less?). Take a look at the functions `_installRuntime` and `install`. The error is most likely located in or around there.

**Comment by Zemogiter** [comment]
I went through `_installRuntime` and found nothing.

**Comment by madoar** [comment]
Have you perhaps made any changes to your local repository?

**Comment by Zemogiter** [comment]
No.

**Comment by madoar** [comment]
When exactly does this error occur? It should occur during engine installation. Does it occur for all installer scripts (i.e. also for `Notepad++` etc.) or only for a certain few? Is there a way to easily reproduce the error?

**Comment by Zemogiter** [comment]
In `Notepad++' case the error appears right after the script finishes checking file integrity.

**Comment by madoar** [comment]
I can't reproduce the issue with `Notepad++`. I've tried with a removed `.Phoenicis` folder and a the current master branch of Phoenicis.
