### ISSUE TITLE
vcrun2010 fails to install

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1145]
Happens right after the vcredist.exe file is downloaded. Oddly enough, on 32 bit prefix the 32 bit executable crashes but not on 64 bit prefix.
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Error while parsing the registry
	at org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:77)
	at <js> fetchValue(Unnamed:73-74:2035-2150)
	at <js> getWindowsVersion(Unnamed:13:287-373)
	at <js> go(Unnamed:22:572-620)
	at <js> :anonymous(Unnamed:24:890-912)
	at <js> go(Unnamed:83:3245-3279)
	at com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy68.go(Unknown Source)
	at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalArgumentException: Error while parsing the registry
```
Using `vcrun2010` on 64 bit prefix results in 64 bit executable crashing with the same error.
Winetricks works fine.

**Comment by Zemogiter** [comment]
No longer able to repoduce since applying #1152 and POL5's latest commit. Closing.
