### ISSUE TITLE
Starcraft download fails

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1172]
At some point in the progress bar, the download crashes:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Download of https://eu.battle.net/download/getInstaller?os=win&installer=StarCraft-II-Setup.exe has failed
	at org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:307)
	at org.phoenicis.tools.http.Downloader.get(Downloader.java:260)
	at org.phoenicis.tools.http.Downloader.get(Downloader.java:237)
	at org.phoenicis.tools.http.Downloader.get(Downloader.java:101)
	at org.phoenicis.tools.http.Downloader.get(Downloader.java:81)
	at <js> get(Unnamed:135-144:3540-3841)
	at <js> _installationCommand(Unnamed:41-46:1190-1352)
	at <js> go(Unnamed:29:1044-1081)
	at com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy68.go(Unknown Source)
	at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.tools.http.DownloadException: Download of https://eu.battle.net/download/getInstaller?os=win&installer=StarCraft-II-Setup.exe has failed

[WARNING] 
org.graalvm.polyglot.PolyglotException: Download of https://eu.battle.net/download/getInstaller?os=win&installer=StarCraft-II-Setup.exe has failed
    at org.phoenicis.tools.http.Downloader.saveConnectionToStream (Downloader.java:307)
    at org.phoenicis.tools.http.Downloader.get (Downloader.java:260)
    at org.phoenicis.tools.http.Downloader.get (Downloader.java:237)
    at org.phoenicis.tools.http.Downloader.get (Downloader.java:101)
    at org.phoenicis.tools.http.Downloader.get (Downloader.java:81)
    at <js>.get (Unnamed:135)
    at <js>._installationCommand (Unnamed:41)
    at <js>.go (Unnamed:29)
    at com.oracle.truffle.polyglot.ObjectProxyHandler.invoke (HostInteropReflect.java:678)
    at com.sun.proxy.$Proxy68.go (Unknown Source)
    at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7 (ApplicationInformationPanelSkin.java:237)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```
Entering the url in browser results in a downloaded file so this may be on our end.

**Comment by madoar** [comment]
There is some part of the error message missing (i.e. what exactly caused the error)

**Comment by Zemogiter** [comment]
Tried the script again and I can't reproduce it anymore.

**Comment by plata** [comment]
Can we close the issue then?

**Comment by Zemogiter** [comment]
I think so
