### ISSUE TITLE
Game Road Rash installation leads to a Java error

### ISSUE THREAD

**Issue by Dadu042** [PhoenicisOrg/scripts#1260]
Tested on Linux Xubuntu 22.04:

```
...
14:46:33.385 [INFO ] org.phoenicis.tools.archive.Zip (l.91) - Creating output file /home/dadu042/.Phoenicis/containers/wineprefix/Road Rash/drive_c/Road Rash/RoadRash/TEXT/ITA.DLL.
14:46:33.468 [ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: com.oracle.truffle.api.interop.UnsupportedTypeException: Cannot convert '/home/dadu042/.Phoenicis/containers/wineprefix/Road Rash/drive_c/Road Rash/RoadRash/RASH.REG'(language: Java, type: java.io.File) to Java type 'java.lang.String': Unsupported target type.
	at <js> run(Unnamed:415:15806-15854)
	at <js> run(Unnamed:172:5961-6051)
	at <js> open(Unnamed:34:928-1001)
	at <js> :=>(Unnamed:20:705-743)
	at <js> go(Unnamed:82:2573-2608)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:694)
	at com.sun.proxy.$Proxy60.go(Unknown Source)
	at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:271)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by plata** [comment]
https://github.com/PhoenicisOrg/phoenicis/blob/466fa3a0e88720699e8f40c1926a98f839963d47/phoenicis-tools/src/main/java/org/phoenicis/tools/files/FileSearcher.java#L37 does indeed return a list of files.

Replacing https://github.com/PhoenicisOrg/scripts/blob/fe1f1234980267e48c5f06c7ad7b508e5167e3cf/Applications/Games/Road%20Rash/Online/script.js#L16
with
```Javascript
new Regedit(wine).open(registryFile[0].getAbsolutePath());
```
should work.
