### ISSUE TITLE
Battle.net : unable to create temporary file

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/Scripts#377]
When trying to install Battle.net
```
java.lang.RuntimeException: java.io.IOException: Unable to create temporary file, /home/fevrier
/.Phoenicis/tmp/phoenicis4737179577105566379.net/download/getInstallerForGame?os=win&locale=enGB&version=LIVE&gameProgram=BATTLENET_APP
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to create temporary file, /home/fevrier/.Phoenicis/tmp/phoenicis4737179577105566379.net/download/getInstallerForGame?os=win&locale=enGB&version=LIVE&gameProgram=BATTLENET_APP
	at java.io.File$TempDirectory.generateFile(File.java:1921)
	at java.io.File.createTempFile(File.java:2010)
	at org.phoenicis.tools.files.FileUtilities.createTmpFile(FileUtilities.java:104)
	at jdk.nashorn.internal.scripts.Script$Recompilation$236$1357A$\^eval\_.createTempFile([Utils, Functions, Filesystem, Files]:48)
	at jdk.nashorn.internal.scripts.Script$Recompilation$235$866A$\^eval\_._installationCommand([Engines, Wine, QuickScript, OnlineInstallerScript]:38)
	at jdk.nashorn.internal.scripts.Script$Recompilation$234$611$\^eval\_.go([Engines, Wine, QuickScript, InstallerScript]:33)
	at jdk.nashorn.internal.scripts.Script$209$\^eval\_.:program(<eval>:5)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	... 11 more

```

**Comment by plata** [comment]
The problem is that `createTempFile` needs a file extension (I don't know why). `OnlineInstallerScript` determines this by splitting at `.`. As there is not `.` in the URL, the complete URL is used as extension which results in an invalid file name.
