### ISSUE TITLE
SteamScript crashes when using .wineArchitecture

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#620]
Tried two diffirent scripts for two steam games (Space Engineers and Subnautica) and right after the script downloads SteamInstaller.exe it crashes with this:

TypeError:new Wine().wizzard(setupWizzard).architecture is not a funciton in [engines,wine,quick_script,steam_script] at line number 98
``
javax.script.ScriptException: TypeError: new Wine().wizard(setupWizard).architecture is not a function in [engines, wine, quick_script, steam_script] at line number 98
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: [engines, wine, quick_script, steam_script]:98 TypeError: new Wine().wizard(setupWizard).architecture is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$600$2195$\^eval\_.go([engines, wine, quick_script, steam_script]:98)
	at jdk.nashorn.internal.scripts.Script$Recompilation$586$551$\^eval\_.run(<eval>:16)
	at org.phoenicis.scripts.Installer$$NashornJavaAdapter.run(Unknown Source)
	at jdk.nashorn.internal.scripts.Script$553$\^eval\_.:program(<eval>:42)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 10 more
``

I've looked at the file mentioned in that error and there is a function that creates a new wineprefix with architecture taken from the script so I have no idea why this error shows up. I've also looked at https://phoenicisorg.github.io/scripts/script-js/ in case the way script.js should be written have changed but that is not the case. Also tried this with a script not made by me (Assasin's Creed Unity) and the same thing happend.

**Comment by plata** [comment]
Can you try to change in `Engines/Wine/QuickScript/Steam Script/script.js`?:
from
```Javascript
    var wine = new Wine()
        .wizard(setupWizard)
        .architecture(this._wineArchitecture)
        .distribution(this._wineDistribution)
        .version(this._wineVersion)
        .prefix(this._name)
```
to
```Javascript
    var wine = new Wine()
        .wizard(setupWizard)
        .prefix(this._name, this._wineDistribution, this._wineArchitecture, this._wineVersion)
```

**Comment by Zemogiter** [comment]
This fixes the error but introduces another one (at least I think so)- once file consistency check is done the script becomes stuck on "Please wait while wine?os=linux is downloaded". Could be something else blocking the script progression.
[phoenicis.log](https://github.com/PhoenicisOrg/scripts/files/1995471/phoenicis.log)

**Comment by plata** [comment]
No idea for that issue currently. Might be that the download of the Wine versions JSON is slow. Can you provide a pull request with the fix?
