### ISSUE TITLE
DXVK crashes with TypeError: wine.dxvk is not a function in <eval> at line number 28

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#659]
Full log:
```
javax.script.ScriptException: TypeError: wine.dxvk is not a function in <eval> at line number 28
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:28 TypeError: wine.dxvk is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1971$902AA$\^eval\_.run#L:24(<eval>:28)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1936$2195$\^eval\_.go([engines, wine, quick_script, steam_script]:110)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1922$499$\^eval\_.run(<eval>:15)
	at org.phoenicis.scripts.Installer$$NashornJavaAdapter.run(Unknown Source)
	at jdk.nashorn.internal.scripts.Script$1888$\^eval\_.:program(<eval>:41)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 10 more
```
Local repo up to date. Crash happens when installing Space Engineers (script for that game is still WIP since I have yet to run it on POL4 or vanilla Wine or Lutris). 
BTW, script for DXVK needs to be updated because it now requires wine 3.10 minimum.

**Comment by ImperatorS79** [comment]
First, remember you cannot use wine versions from POL because they do not support vulkan.
Normally the function should be `wine.DXVK();` instead of `wine.dxvk;`

**Comment by Zemogiter** [comment]
But we do have an vulkanSDK verb. Isn't that enough for a windows application to access DXVK?

**Comment by ImperatorS79** [comment]
When compiling wine, it has to be compiled with libvulkan-dev, otherwise winevulkan won't be build.
VulkanSDK verb is only needed for vulkan-1.dll, which is not implemented in wine before version 3.5 (and for high debugging purpose after 3.5).

**Comment by ImperatorS79** [comment]
Is the error gone ?

**Comment by Zemogiter** [comment]
Yes.
