### ISSUE TITLE
Failed to install Microsoft Office Professional 2010

### ISSUE THREAD

**Issue by pmorch** [PhoenicisOrg/scripts#704]
### Expected behavior

It should install

I realize MS Office 2010 is considered "testing" so consider this test feedback... ;-)

### Actual behavior

It seems to hang indefinitely (at least 40min+): 

### Steps to reproduce
* Start with a fresh Xubuntu 18.04 installation
* Follow [Build | Phoenicis Documentation](https://phoenicisorg.github.io/phoenicis/Users/build/)
* Hit and work around #1402 
* Try to install e.g. MS Office 2010
* It chugs along, downloads and installs various things but eventually gets stuck here:
![pleasewait](https://user-images.githubusercontent.com/159292/46583001-1a2ab100-ca50-11e8-88d7-9092b97de555.png)
![officeinstalling](https://user-images.githubusercontent.com/159292/46583003-1e56ce80-ca50-11e8-9394-c70f16663039.png)
![top](https://user-images.githubusercontent.com/159292/46583004-231b8280-ca50-11e8-9e2d-1290309232d3.png)
This [secondrun.txt](https://github.com/PhoenicisOrg/phoenicis/files/2454005/secondrun.txt) is the log file from my second run ( after working around #1402 ) but it hasn't changed in hours...

### System information
* software version (git revision) of phoenicis

```
test@xfce1804:~/phoenicis$ git log -1
commit c571d6c1db11eb72f2b370893b98575be4e088e5 (HEAD -> master, origin/master, origin/HEAD)
Author: plata <plata@users.noreply.github.com>
Date:   Fri Sep 28 20:02:53 2018 +0200

    Add support for JDK 11 (#1404)

```
... and scripts repositories

? How do I determine that?

* Just updated Xubuntu 18.04

* used Java version

```
test@xfce1804:~/phoenicis$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
test@xfce1804:~/phoenicis$ dpkg-query -W | grep openjdk
openjdk-11-jre-headless:amd64	10.0.2+13-1ubuntu0.18.04.2
openjdk-8-jdk:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jdk-headless:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jre:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jre-headless:amd64	8u181-b13-0ubuntu0.18.04.1
```

**Comment by ovari** [comment]
Can the [Office 2010 script for POL4](https://www.playonlinux.com/en/app-801.html) please be updated? Perhaps the [Office 2010 script for POL5/Phoenicis](https://github.com/PhoenicisOrg/scripts/tree/master/Applications/Office/Microsoft%20Office%202010) needs updating too?

Error installing **only** Outlook 2010 using the Office 2010 script.

- What were you doing when the problem occurred?
Installing only Outlook 2010 from Office 2010

- What did you expect?
POL should not try to create shortcuts for:
WINWORD.EXE
EXCEL.EXE
POWERPNT.EXE
ONENOTE.EXE
POL should not create Extension for:
doc
docx
xls
xlsx
ppt
pptx

- What happened instead?
Error messages saying these files were not found, which is true because these programs were not installed.

- Anything else to report?
Could the script be updated with `if` statements?
The current code:
```
POL_Shortcut "WINWORD.EXE" "Microsoft Word 2010" "" "" "Office;WordProcessor;"
POL_Shortcut "EXCEL.EXE" "Microsoft Excel 2010" "" "" "Office;Spreadsheet;"
POL_Shortcut "POWERPNT.EXE" "Microsoft Powerpoint 2010" "" "" "Office;Presentation;"
POL_Shortcut "ONENOTE.EXE" "Microsoft OneNote 2010" "" "" "Network;InstantMessaging;" # No category for collaborative work?
POL_Shortcut "OUTLOOK.EXE" "Microsoft Outlook 2010" "" "" "Network;Email;" # Calendar;ContactManagement; ? :p
  
POL_Extension_Write doc "Microsoft Word 2010"
POL_Extension_Write docx "Microsoft Word 2010"
POL_Extension_Write xls "Microsoft Excel 2010"
POL_Extension_Write xlsx "Microsoft Excel 2010"
POL_Extension_Write ppt "Microsoft Powerpoint 2010"
POL_Extension_Write pptx "Microsoft Powerpoint 2010"
  
if [ "$POL_OS" = "Mac" ]; then
    POL_Shortcut_InsertBeforeWine "Microsoft Word 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    POL_Shortcut_InsertBeforeWine "Microsoft Excel 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    POL_Shortcut_InsertBeforeWine "Microsoft Powerpoint 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    POL_Shortcut_InsertBeforeWine "Microsoft OneNote 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    POL_Shortcut_InsertBeforeWine "Microsoft Outlook 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
fi
```
could be replaced with (Not sure how to check if a file exists. Is the [function listed](http://wiki.playonlinux.com/index.php/Scripting_-_Chapter_11:_List_of_Functions)?):

```
if [ "$(POL_File_Exists WINWORD.EXE)" = "True" ]
then
    POL_Shortcut "WINWORD.EXE" "Microsoft Word 2010" "" "" "Office;WordProcessor;"
    POL_Extension_Write doc "Microsoft Word 2010"
    POL_Extension_Write docx "Microsoft Word 2010"
    if [ "$POL_OS" = "Mac" ]; then
        POL_Shortcut_InsertBeforeWine "Microsoft Word 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    fi
fi

if [ "$(POL_File_Exists EXCEL.EXE)" = "True" ]
then
    POL_Shortcut "EXCEL.EXE" "Microsoft Excel 2010" "" "" "Office;Spreadsheet;"
    POL_Extension_Write xls "Microsoft Excel 2010"
    POL_Extension_Write xlsx "Microsoft Excel 2010"
    if [ "$POL_OS" = "Mac" ]; then
        POL_Shortcut_InsertBeforeWine "Microsoft Excel 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""

    fi
fi

if [ "$(POL_File_Exists POWERPNT.EXE)" = "True" ]
then
    POL_Shortcut "POWERPNT.EXE" "Microsoft Powerpoint 2010" "" "" "Office;Presentation;"
    POL_Extension_Write ppt "Microsoft Powerpoint 2010"
    POL_Extension_Write pptx "Microsoft Powerpoint 2010"
    if [ "$POL_OS" = "Mac" ]; then
        POL_Shortcut_InsertBeforeWine "Microsoft Powerpoint 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    fi
fi

if [ "$(POL_File_Exists ONENOTE.EXE)" = "True" ]
then
    POL_Shortcut "ONENOTE.EXE" "Microsoft OneNote 2010" "" "" "Network;InstantMessaging;" # No category for collaborative work?
    if [ "$POL_OS" = "Mac" ]; then
        POL_Shortcut_InsertBeforeWine "Microsoft OneNote 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    fi
fi

if [ "$(POL_File_Exists OUTLOOK.EXE)" = "True" ]
then
    POL_Shortcut "OUTLOOK.EXE" "Microsoft Outlook 2010" "" "" "Network;Email;" # Calendar;ContactManagement; ? :p
    if [ "$POL_OS" = "Mac" ]; then
        POL_Shortcut_InsertBeforeWine "Microsoft Outlook 2010" "source \"$POL_USER_ROOT/tools/samba3/init\""
    fi
fi
```

**Comment by Sobuj53** [comment]
> @pmorch Would you mind trying with my git repo here https://github.com/ImperatorS79/Scripts/tree/Office2010 ? You can change the repo you want to use in the parameters tab.

Hello I'm having the same issue as this one. I've tried to add your repo in POL 5 from, Settings>Repositories>Add. I add the URL Git-URL box and in Git-Branch: Office2010 which results in following error,

> org.phoenicis.repository.RepositoryException: Could not clone or update git repository
	at org.phoenicis.repository.types.GitRepository.fetchInstallableApplications(GitRepository.java:167)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:575)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: org.phoenicis.repository.RepositoryException: Folder '/home/sobuj/.Phoenicis/cache/git-1539419275' is no git-repository
	at org.phoenicis.repository.types.GitRepository.cloneOrUpdate(GitRepository.java:124)
	at org.phoenicis.repository.types.GitRepository.cloneOrUpdateWithLock(GitRepository.java:89)
	at org.phoenicis.repository.types.GitRepository.fetchInstallableApplications(GitRepository.java:163)
	... 12 more
Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:252)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:302)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.phoenicis.repository.types.GitRepository.cloneOrUpdate(GitRepository.java:121)
	... 14 more
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: https://github.com/ImperatorS79/Scripts/tree/Office2010: https://github.com/ImperatorS79/Scripts/tree/Office2010/info/refs?service=git-upload-pack not found: Not Found
	at org.eclipse.jgit.transport.TransportHttp.createNotFoundException(TransportHttp.java:522)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:554)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:392)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:138)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1292)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	... 17 more

**Comment by plata** [comment]
@ImperatorS79 could you have a look (apparently @Sobuj53 is using your repository and I'm not sure about it's state or if this branch even exists anymore)?

**Comment by ImperatorS79** [comment]
@Sobuj53 you can try my new Office2010 branch in my fork. I did not test it though.

**Comment by Sobuj53** [comment]
@ImperatorS79 thank you for your reply. I was able to successfully add your fork in POL 5 repo, but the issue is, it gets stuck while applying updates. I've been waiting to complete the installation process for more than 3 hrs now, but still it's stuck in applying updates window!

**Comment by ImperatorS79** [comment]
So there is no error anymore in the log but the installation loops infinitely (if I understand well) ?

**Comment by Sobuj53** [comment]
yes, there is no error just hanging in there. I think I should remove all the update file from the installation directory and try again to see if anything changes or not

**Comment by Sobuj53** [comment]
ok so this time I was able to successfully complete the installation process after removing all update files from the update folder but sadly it didn't create the program shortcut :(

**Comment by ismailkhan5356** [comment]
# [Download Microsoft Office 2007 ⏬🔽💹](https://94fbr.xyz/click-go-to-download/)
