### ISSUE TITLE
Adobe Acrobat script - download of W2ksp4_EN.exe has failed

### ISSUE THREAD

**Issue by mlaradji** [PhoenicisOrg/scripts#706]
I attempted to install Adobe Acrobat Reader DC through the repository Phoenicis  (GUI) script, but the script fails to complete due to an error in downloading one of the prerequisite packages. The log shows the following error:
```
12:44:07.201 [ERROR] org.phoenicis.javafx.views.common.ErrorMessage (l.75) - org.phoenicis.tools.http.DownloadException: Download of http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe has failed
        at org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:172)
        at org.phoenicis.tools.http.Downloader.get(Downloader.java:127)
        at org.phoenicis.tools.http.Downloader.get(Downloader.java:72)
        at org.phoenicis.tools.http.Downloader.get(Downloader.java:58)
        at jdk.nashorn.internal.scripts.Script$Recompilation$371$2364$\^eval\_.get([utils, functions, net, download]:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$390$1795$\^eval\_.get([utils, functions, net, resource]:101)
        at jdk.nashorn.internal.scripts.Script$Recompilation$398$365$\^eval\_.mspatcha([engines, wine, verbs, mspatcha]:14)
        at jdk.nashorn.internal.scripts.Script$Recompilation$397$945AA$\^eval\_.run#L:21(<eval>:22)
        at jdk.nashorn.internal.scripts.Script$Recompilation$362$565$\^eval\_.go([engines, wine, quick_script, installer_script]:75)
        at jdk.nashorn.internal.scripts.Script$Recompilation$347$286$\^eval\_.run(<eval>:10)
        at org.phoenicis.scripts.Installer$$NashornJavaAdapter.run(Unknown Source)
        at jdk.nashorn.internal.scripts.Script$320$\^eval\_.:program(<eval>:31)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
        at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:145)
        ... 25 more
```

## Discussion
Attempting to access the URL (http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe) through the browser returns a 404 error. This might be the source of the problem.

A similar issue is Winetricks/winetricks#600.

**Comment by plata** [comment]
Winetricks uses: https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE with checksum 167bb78d4adc957cc39fb4902517e1f32b1e62092353be5f8fb9ee647642de7e. Can you try if that works?

**Comment by plata** [comment]
I also saw that link in the winetricks issue you linked. I think using the same URL as winetricks is the correct approach.
