### ISSUE TITLE
QA: referenceError: "LocalInstallerScript" is not defined in <eval> at line number 24

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#816]
Results in https://paste.pound-python.org/show/L8Z9n70JqghEepjNMKYd/ on Online.

Need more info.

script.js on https://github.com/PhoenicisOrg/scripts/blob/3463e16561ef6fc0b34eb96ff4187902e94b4a40/Applications/Games/SMITE/Online/script.js

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/814#issuecomment-453924162_

**Comment by ImperatorS79** [comment]
You include at the beginning of the script an online installer instead of a local one.

**Comment by Kreyren** [comment]
> You include an online installer instead of a local one at the beginning of the script.

Moved to merge review

**Comment by plata** [comment]
Please don't ask about stuff like this in a separate issue. Like you said yourself, this is something for a pull request.

**Comment by Kreyren** [comment]
@plata I wanted to separate the issues that are related to merge request from issues that are general and non relevant to merge. Sane?

**Comment by plata** [comment]
Generally yes. But like @ImperatorS79 pointed out, this is not a general issue but very special to the way you wrote your script.

**Comment by Kreyren** [comment]
Checking

**Comment by Kreyren** [comment]
Nope same issue on StarCraft II 
![image](https://user-images.githubusercontent.com/11302521/51134932-26858d80-1839-11e9-93e0-a282de2c8888.png)

```
javax.script.ScriptException: Executable StarCraft II.exe not found! in <eval> at line number 121 at column number 8
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: <eval>:121:8 Executable StarCraft II.exe not found!
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$325$2842$\^eval\_$cu1$restOf.create([engines, wine, shortcuts, wine]:121)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$320$3037A$\^eval\_$cu1$restOf._createShortcut([engines, wine, quick_script, quick_script]:132)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$306$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:87)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$62$315$\^eval\_.run(<eval>:11)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$61$\^eval\_$cu1$restOf.:program(<eval>:33)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more
```

**Comment by Kreyren** [comment]
@ImperatorS79 Can you reproduce on a account that is protected by authentificator?
