### ISSUE TITLE
BUG: Adobeair verb

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#819]
![image](https://user-images.githubusercontent.com/11302521/51170138-f926f700-18ad-11e9-9d6b-fcd2b7424b58.png)

if league of legends from KREY-PhoenicisOrg:leagueoflegends is installed with master on adobeair the installer fails with:

```
java.lang.IllegalMonitorStateException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$360$303$\^eval\_$cu1$restOf.adobeair([engines, wine, verbs, adobeair]:22)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$268$4650AA$\^eval\_.run#L:99(<eval>:105)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$211$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:75)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$136$663$\^eval\_.run(<eval>:19)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$135$\^eval\_$cu1$restOf.:program(<eval>:123)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Suspect that adobeair window that is called triggers this error.

### References
https://github.com/PhoenicisOrg/scripts/pull/797

**Comment by Zemogiter** [comment]
I have the exact same error. Tried removing setting the OS to winxp but it changed nothing.

**Comment by madoar** [comment]
The issue is in line: https://github.com/PhoenicisOrg/scripts/blob/4f809342ad4fbe495b72c804d23c279fde68c3c1/Engines/Wine/Verbs/adobeair/script.js#L21

`Object#wait` should only be executed in `synchronized` blocks in java.
@qparis, @plata I think we will need to either change the script to not use `wait` (I don't think this is possible) or to add `synchronized` somewhere on the Java side.
What do you think?

**Comment by Kreyren** [comment]
Recommends using silent installer for adobeair (again).. it's workaround for multiple windows environments also.

**Comment by madoar** [comment]
@plata it must be `Object#wait`, otherwise the exception shouldn't fail at `java.base/java.lang.Object.wait(Native Method)`

**Comment by Zemogiter** [comment]
@plata your solution works. Will make a PR right now.

**Comment by plata** [comment]
@madoar yes. This is what it does but not what was intended.

@Zemogiter that's also a solution. In this case simply remove `.wait()`.

**Comment by madoar** [comment]
@plata ok. Do you know why the method chaining doesn't work as intended?

**Comment by plata** [comment]
`run` is in the engine implementation now (i.e. the generic part of the engine which implements the Java interface).
