### ISSUE TITLE
QA/BUG: Unable to extract the file.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#821]
My OverWatch script on https://github.com/PhoenicisOrg/scripts/pull/783 is unable to extract a file, need more info

```
org.phoenicis.tools.archive.ArchiveException: Unable to extract the file
	at org.phoenicis.tools.archive.Tar.uncompress(Tar.java:199)
	at org.phoenicis.tools.archive.Tar.uncompressTarFile(Tar.java:89)
	at org.phoenicis.tools.archive.Extractor.uncompress(Extractor.java:69)
	at org.phoenicis.tools.archive.Extractor.uncompress(Extractor.java:45)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$289$3124$\^eval\_$cu1$restOf.extract-1([utils, functions, filesystem, extract]:140)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$281$438A$\^eval\_$cu1$restOf.DXVK([engines, wine, verbs, dxvk]:36)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$203$1137AA$\^eval\_.run#L:26(<eval>:31)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$123$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:75)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$69$468$\^eval\_.run(<eval>:14)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$68$\^eval\_$cu1$restOf.:program(<eval>:40)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Error detected parsing the header
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:285)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:552)
	at org.phoenicis.tools.archive.Tar.uncompress(Tar.java:160)
	... 24 more
Caused by: java.lang.IllegalArgumentException: Invalid byte 56 at offset 4 in '06558568' len=8
	at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:141)
	at org.apache.commons.compress.archivers.tar.TarUtils.parseOctalOrBinary(TarUtils.java:171)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1277)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1266)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:404)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:283)
	... 26 more
```

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/783#issuecomment-454415697_

**Comment by Kreyren** [comment]
@ImperatorS79 Thanks for info, will do
