### ISSUE TITLE
QA: Steam - Browser not working

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#961]
While steam is installed from phoenicis it's browser is not working 
![image](https://user-images.githubusercontent.com/11302521/58979551-ea28de80-8793-11e9-9412-c1743e5087e6.png)

Suspect missing corefonts -> Same Issue, corefonts irelevant.

**Comment by ImperatorS79** [comment]
Then install corefonts and you will see ^^.

**Comment by Kreyren** [comment]
> Then install corefonts and you will see ^^.

Thats what i'm doing atm

**Comment by Kreyren** [comment]
From https://appdb.winehq.org/objectManager.php?sClass=version&iId=19444 

> https://appdb.winehq.org/objectManager.php?sClass=version&iId=19444

Testing

**Comment by ImperatorS79** [comment]
I am not sure ntml_auth is in the runtime though.

**Comment by Kreyren** [comment]
I made it work: 

![image](https://user-images.githubusercontent.com/11302521/58982519-3ecf5800-879a-11e9-9924-3cd3a89c4621.png)

steam.exe && steamwebhelper.exe has to be set on winxp for browser to work

corefonts also mandatory

Tested using wine staging x86 4.8

**Comment by Kreyren** [comment]
Noticed new build started.. now it fails with
```
javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found eof

^ in engines.wine.engine.implementation at line number 124
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: engines.wine.engine.implementation:124 SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found eof

^
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:160)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:145)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81)
	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:118)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1503$4170A$\^eval\_$cu1$restOf._installRuntime(engines.wine.engine.implementation:124)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1498$1596AA$\^eval\_$cu1$restOf.install(engines.wine.engine.implementation:36)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1496$11334AAAZZA$\^eval\_$cu1$restOf.run(engines.wine.engine.implementation:297)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1488$4949AAAZZA$\^eval\_.run(engines.wine.engine.object:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1487$219A$\^eval\_$cu1$restOf.regedit#open(engines.wine.plugins.regedit:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1473$287$\^eval\_$cu1$restOf.luna(engines.wine.verbs.luna:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1440$493$\^eval\_$cu1$restOf.go(engines.wine.quick_script.installer_script:72)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1376$340$\^eval\_.run(<eval>:11)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1375$\^eval\_$cu1$restOf.:program(<eval>:34)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found eof

^
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:161)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79)
	... 26 more
```

**Comment by Zemogiter** [comment]
I have both .exe set to winxp and corefonts are installed yet browser is broken in Space Engineers. I installed vcrun2008 and vcrun2015 via winetricks on a POL4 x32 prefix for Civilization5.
